spring:
  # --- KAFKA CONSUMER CONFIG ---
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

# --- LOGGING CONFIG ---
logging:
  level:
    org.apache.kafka: INFO
    root: info

# --- CUSTOM APPLICATION PROPERTIES (Biznis nastavenia, E-maily) ---
app:
  events:
    version: 1
  # Change to gmail or another email provider
  email:
    provider: ${EMAIL_PROVIDER}
    # sendgrid provider
    sendgrid:
      api-key: "ss"
      from-email: richardkovacik.123@gmail.com
      from-name: Coffessino
      host: https://api.sendgrid.com
      uri: /v3/mail/send
      connection-timeout: PT3S
      read-timeout: PT5S
    # resend.com provider
    resend:
      api-key: ${RESEND_API_KEY}
      from-email: onboarding@resend.dev
      from-name: Coffesino DEV Team
      host: ${RESEND_HOST}
      uri: ${RESEND_URI}
      connection-timeout: PT3S
      read-timeout: PT5S